name: CI/CD

on: [push]

jobs:
  build:
    # env:
    #   DOCKER_ACCOUNT: sogis
    #   DOCKER_REPO: standortkarte
    #   DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #   DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
    #   BUILD_NUMBER: ${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup Java 11'
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image
